hw strams task3 has been done
bumax1989/JIS7 pull request #17
Opened 2021-05-28 15:59 UTC by bumax1989

2021-05-29 09:41 UTC, KaydunovDenis requested changes

2021-05-29 09:41 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +package homework.lectures.lecture8_streams.product_collection_stream;
See name your pull request)))

2021-05-29 09:41 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +        System.out.println(minPriceValueAndMaxDiscountValue);
productRepository.getListProducts().stream()
                .min(Comparator.comparing(Product::getPrice)
                        .thenComparing((o1, o2) -> Double.compare(o2.getDiscount(), o1.getDiscount())))
                .ifPresent(System.out::println);

2021-06-05 06:20 UTC, ArtikTico reviewed
Чекай комменты

2021-06-05 06:20 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .get();
get() - можешь получить NPE. После компаратора так значения не достаются

2021-06-05 06:20 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .collect(Collectors.toList());
Выделяй методы и нажимай Ctrl + Alt + L чтобы отформатировать по конвенции. Обрати внимание у тебя в некоторых местах пробелов не хватает

2021-06-07 19:38 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +package homework.lectures.lecture8_streams.product_collection_stream;
а что не так?

2021-06-09 18:06 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +package homework.lectures.lecture8_streams.product_collection_stream;
strams ->streams))

2021-06-09 18:08 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .collect(Collectors.toList());
Влад оговаривался, что даже можно не выделять ничего, просто Ctrl + Alt + L и оно исправит во всем файле

2021-06-09 18:09 UTC, KaydunovDenis approved these changes

2021-06-18 18:37 UTC, ArtikTico reviewed
Чекни комменты

2021-06-18 18:37 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .get();
Возвращать get плохая практика

2021-06-18 18:37 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .get();
Старайся не пользоваться этим методом.

2021-06-20 17:04 UTC, bumax1989 reviewed
All Done

2021-06-20 17:04 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .get();
там есть проверка на null

2021-06-20 17:04 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .collect(Collectors.toList());
Устранено

2021-06-20 17:04 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +        System.out.println(minPriceValueAndMaxDiscountValue);
Можно и так, спасибо, но я тут разделял по подпунктам ;)

2021-06-20 17:04 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .get();
> Старайся не пользоваться этим методом.

договорились, но чуть выше есть фильтрация объектам
`.filter(Objects::nonNull)`

2021-06-28 09:24 UTC, KaydunovDenis approved these changes

2021-06-28 09:26 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/product_collection_stream/App.java
> +                .get();
И что с этим делать?  Поможет эта проверка? идея все равно ругается.

2021-07-02 07:13 UTC, merged