hw strams task4 has been done
bumax1989/JIS7 pull request #18
Opened 2021-05-28 19:11 UTC by bumax1989

2021-05-29 09:49 UTC, KaydunovDenis requested changes

2021-05-29 09:49 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/sort_products/Product.java
> +    }
use lombok

2021-05-29 09:49 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/sort_products/App.java
> +        System.out.println(sortedListByPrice);
Что отсортировать по одному  а потом по другому можно использовать компаратор.
Через компаратор можно настроить сортировку как угодно.

Comparator.comparing(Product::getDiscount)
                        .thenComparing(////.........)   .thenComparing...........

а потом просто используем:
stream()
.sorted(comporator)

2021-06-05 06:16 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/sort_products/App.java
> +        System.out.println(sortedListByPrice);
Максим тут прислушайся к совету Дениса. Это избыточно делать в разных стримах а потом еще и конкатенировать их

2021-06-05 06:17 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/sort_products/Product.java
> +    }
Ломбок это на любителя, я не заставляю) 
Как удобно так и используй

2021-06-09 18:03 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/sort_products/Product.java
> +    }
@ArtikTico Как его не использовать когда использовал  хотя бы раз)

2021-06-09 18:05 UTC, KaydunovDenis approved these changes
Cool!

2021-06-18 18:38 UTC, ArtikTico approved these changes

2021-06-18 18:38 UTC, merged