HW User has been done
bumax1989/JIS7 pull request #19
Opened 2021-06-04 19:49 UTC by bumax1989

2021-06-05 06:15 UTC, ArtikTico reviewed
Чекай комменты. Решение норм, исправь недочеты

2021-06-05 06:15 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +                        it.setUserStatus(UserStatus.VIPUSER);
`VIPUSER` -> `VIP_USER` название Enum переменных разделяется нижними подчеркиваниями. FULL_ACTIVE_USER  например так

2021-06-05 06:15 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +
тут пробел лишний

2021-06-05 06:15 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/user/UserStatus.java
> +    VIPUSER
Читай выше

2021-06-07 18:47 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/user/UserStatus.java
> +    VIPUSER
Исправил, спасибо

2021-06-07 18:48 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +                        it.setUserStatus(UserStatus.VIPUSER);
Исправил

2021-06-07 18:48 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +
Исправил

2021-06-08 13:43 UTC, KaydunovDenis requested changes

2021-06-08 13:43 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/user/UserImplementationService.java
> +public class UserImplementationService {
Некорректное наименование класса.
Насколько я разбираюсь, этот класс ничего не реализует(не имплементит).
Этот класс скорее как база данных - UserRepository

2021-06-08 13:43 UTC, KaydunovDenis commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +    public static List<User> changeStatusAndFlag(List<User> userList) {
Change - изменить  - куда изменить ? может быть increase
Status - чей статус

2021-06-18 18:41 UTC, ArtikTico reviewed
Чекай комменты

2021-06-18 18:41 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/user/UserImplementationService.java
> +public class UserImplementationService {
Совершенно верно

2021-06-18 18:41 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +    public static List<User> changeStatusAndFlag(List<User> userList) {
updateUserStatus или increaseUserStatus

2021-06-18 18:41 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +    public static List<User> sortUsersByNickName(List<User> userList) {
Метод называется отсортировать юзеров по имени а внутри происходит засетывание других статусов?
Мааакс ну это совершенно не очевидно.

2021-06-18 18:41 UTC, ArtikTico commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +    public static List<User> getUsersWithStatusUSERAndIsActiveTRUE(List<User> userList) {
Метод пишется в стиле верблюжего регистра не нужно писать слова в верхнем регистре. Только каждая первая буква слова кроме первого.

2021-06-20 17:14 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/user/UserImplementationService.java
> +public class UserImplementationService {
Готово

2021-06-20 17:16 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +    public static List<User> changeStatusAndFlag(List<User> userList) {
готово

2021-06-20 17:16 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +    public static List<User> getUsersWithStatusUSERAndIsActiveTRUE(List<User> userList) {
готово

2021-06-20 17:26 UTC, bumax1989 commented on src/main/java/homework/lectures/lecture8_streams/user/UserService.java
> +    public static List<User> sortUsersByNickName(List<User> userList) {
поправил

2021-07-02 07:13 UTC, ArtikTico approved these changes
good job

2021-07-02 07:13 UTC, merged